### ISSUE TITLE
Cara Connecting

### ISSUE THREAD

**Issue by Bintangp02** [alpin1234567/Zhirrr-Api#1]
Ind | Cara Connecting  Heroku Ke Github di android gimana cara nya?

Ing | How to Connecting Heroku to Github on android How his way?

**Comment by alpin1234567** [comment]
Silakan cek di YouTube saya mas nama YouTube Alpin OFC dan jika kurang jls
bisa ke wa saya wa.me//+18184035922

Pada tanggal Kam, 18 Mar 2021 08.39 Bintangp02 ***@***.***
menulis:

**Comment by alpin1234567** [comment]
Thanks, I'll check it out.

Pada tanggal Rab, 31 Mar 2021 20.14 Bintangp02 ***@***.***
menulis:
